### PR TITLE
add BPA to s3 bucket

### LINKED ISSUE #32: Add S3 Bucket Public Access Block for FlowLogs S3 Bucket
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* ***If you have submitted a pull request addressing the same issue, please leave a comment!***

***

### Description

To improve security and remove potential misconfiguration of the S3 bucket we need to add S3 bucket block public access bucket by default.

### New or Affected Resource(s)

* aws_s3_bucket_public_access_block

### Potential Terraform Configuration Changes

```hcl
# Copy-paste your Terraform configurations here.
# For large Terraform configs, please use a service like Google Drive and share a link to the ZIP file.
resource "aws_s3_bucket_public_access_block" "this" {
  bucket = "${aws_s3_bucket.this.id}"

  block_public_acls   = true
  block_public_policy = true
}

```

### References

* #0000

### PR DESCRIPTION
**Pull request by ayusun**
### Community Note

* Please vote on this pull request by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original pull request comment to help the community and maintainers prioritize this request
* Please do not leave "+1" comments, they generate extra noise for pull request followers and do not help prioritize the request

***

Fixes #32 

***

Release note for [CHANGELOG](https://github.com/traveloka/terraform-aws-vpc/blob/master/CHANGELOG.md):

```release-note
NOTES:

* Any Notes regarding your submitted PR, like breaking changes or else.

FEATURES:



ENHANCEMENTS:

* feature: Add BPA to S3

BUG FIXES:

* Prevent error from evil bugs
```

***

Output from `terraform plan` command from changes you propose.

```
$ terraform plan

```

### CODE REVIEW

**Review by vincenttjia — DISMISSED** [review]
LGTM

**Comment by vincenttjia** [comment]
Hi @ayusun, please signed your commit and then force push for us to be able to merge your PR. Thank you

```
git reset --soft HEAD~1
```

```
git commit -S -c "comment"
```

```
git push -f origin feature/add-bpa
```

**Comment by ayusun** [comment]
@vincenttjia Signed. Need your help with the review of the PR again.

**Review by vincenttjia — APPROVED** [review]
LGTM

**Pull request merged**
