### PR TITLE
relax provider version for terraform 0.12 readiness

### PR DESCRIPTION
**Pull request by isen-ng**

### CODE REVIEW

**Comment by sshvetsov** [comment]
@isen-ng similar questions as in https://github.com/traveloka/terraform-aws-iam-role/pull/25#issuecomment-496092757. Except in this case, I believe the "random" provider version is already set to `~>1.1` which is equivalent to `>= 1.1` and `< 2.0.0`, so I don't really get what is the problem.

**Comment by isen-ng** [comment]
@sshvetsov In this case, I'm trying to set it to 2.1.2 so that my modules can be terraform 0.12 ready.

Since it's all the same issue, should we continue this discussion in
https://github.com/traveloka/terraform-aws-iam-role/pull/25

**Comment by isen-ng** [comment]
Closing until there is an outcome to the discussion

**Comment by isen-ng** [comment]
Updated to change provider version to `>= 1.2.0, < 3.0.0`, like the iam-roles and resource-naming repos

**Pull request merged**
