### PR TITLE
Additional tags for vpc and subnets

### LINKED ISSUE #21: Allow tagging of VPC and subnets with additional tags
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* ***If you have submitted a pull request addressing the same issue, please leave a comment!***

***

### Description
**New variables needed to store additional tags for VPC, public subnet, app subnet and data subnet.**

- When EKS runs, it creates some additional Kubernetes tags for resources in VPC. 
- If we apply VPC terraform script again, since these tags are not presented in VPC `tf` script, they will be lost.
- That is why we want to have variables so that we can create the Kubernetes tags upfront and store them in the `tf` script itself. This is also to ensure that `tf` script is the *source of truth* .

### New or Affected Resource(s)

* `aws_vpc`
* `"aws_subnet" "public"`
* `"aws_subnet" "app"`
*  `"aws_subnet" "data"`

### Potential Terraform Configuration Changes

```hcl
variable "additional_vpc_tags" {
  description = "A map of additional tags to add to the vpc"
  default     = {}
}

variable "additional_public_subnet_tags" {
  description = "A map of additional tags to add to the public subnet"
  default     = {}
}

variable "additional_app_subnet_tags" {
  description = "A map of additional tags to add to the application subnet"
  default     = {}
}

variable "additional_data_subnet_tags" {
  description = "A map of additional tags to add to the data subnet"
  default     = {}
}
```

### PR DESCRIPTION
**Pull request by billnguyentvlk**
### Community Note

* Please vote on this pull request by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original pull request comment to help the community and maintainers prioritize this request
* Please do not leave "+1" comments, they generate extra noise for pull request followers and do not help prioritize the request

***

Fixes #21 

***

Release note for [CHANGELOG](https://github.com/traveloka/terraform-aws-vpc/blob/master/CHANGELOG.md):

```release-note
ENHANCEMENTS:

* Added `additional_vpc_tags`, `additional_public_subnet_tags`, `additional_app_subnet_tags`, `additional_data_subnet_tags`

```

***

Output from `terraform plan` command from changes you propose.

```
# assuming that these tags are not used after upgrading ..
$ terraform plan
Apply complete! Resources: 0 added, 0 changed, 0 destroyed.

```

### CODE REVIEW

**Comment by billnguyentvlk** [comment]
@sshvetsov The order looks correct to me.
The additional tags are added after `local.common_tags` in `merge`, so they will take precedence over the tags in `local.common_tags`.

https://www.terraform.io/docs/configuration/functions/merge.html

> The additional tags are added in the wrong order. They should be able to override common tags inserted from `local.common_tags`.

**Comment by sshvetsov** [comment]
My bad, the previous message was supposed to read "They should *not* be able to override common tags inserted from `local.common_tags`". Tags like Environment, ProductDomain, should not be overwritable by additional tags, so order is still incorrect.

**Comment by billnguyentvlk** [comment]
Hi @sshvetsov , 
Thanks for the review. I have pushed a new commit to reorder the additional tags. 
Kindly help to review again. Thanks.

**Comment by isen-ng** [comment]
@traveloka/techops
Although this is not urgent, just letting you know we are awaiting your merge, if this looks good to you.

**Pull request merged**
